exts/freeSpotify.json

note that this does conflict with @redstonekasi's `spotifySpoof` (my plugin also has a patch to spoof spotify premium), but i marked it as incompatible so it... should be okay

Added FreeSpotify

---

exts/levantine.json

Levantine is an extension which obfuscates all messages into a format only readable by the viewer in order to prevent shoulder surfing while viewing Discord in public.
By default, the extension converts all text into a pseudo-Japanese format, however a custom "mappings file" can be provided which allows for different types of output.

Add Levantine v1.0.0

---

exts/katex.json

Makes it so that the regex for the KaTeX plugin has a runtime of O(n) rather than O(n²), because for some reason JS RegExp couldn't see that optimization
This prevents the slate editor from stalling for up to hundreds of frames on large inputs

fix katex regex runtime

---

exts/pronouns.json

does the thing
can't load pronouns without opening profile first, apparently not even friends get preloaded in the cache or whatever.

pronouned up

---

exts/remind-me.json

Remind Me enables these Discord experimental tabs in the Inbox and makes them work locally by patching in a client-side store for them:
The real endpoints 404 if you aren't in the corresponding feature rollout.
I have heard of one singular person being in the feature rollout for bookmarks (`2024-06_message_bookmarks`) - and none for reminders (`2022-08_message_todos_staff_only`), so I'm pretty sure this will have at least a good several months of longevity to it.
---
**API Interactions**
- Removed: ~~Fetching messages (cached): [source](https://github.com/karashiiro/moonlight-extensions/blob/53eed4613c7ff79318e4c86b7bee32a72053b019/src/remind-me/webpackModules/savedMessagesShim.ts#L91-L127)~~

Add Remind Me

---

exts/noNotificationSoundExceptDms.json

Adds a plugin that mutes notification sounds except in DMs.

Add No Notification Sound Except DMs

---

exts/pauseTts.json

This extension lets you play ctrl+b to quickly pause/resume an ongoing or queued speech utterance (TTS playback). Very weird in how it works but it works!

Add Pause Text to Speech extension

---

exts/sendTimestamps.json

Adds a .time command to send timestamps written in natural language.
For instance: `.send tomorrow at 2pm` will send a message with a timestamp pointing to "tomorrow at 2pm" local time.
To send in alternative formats, use one of: `.timeshortdate`, `.timelongdate`, `.timelongdateshorttime`, `.timefull`, `.timeshorttime`, `.timelongtime`, `.timerelative`. Defaults to `.timerelative`.
Powered by [Microsoft.Recognizers.Text](https://github.com/microsoft/Recognizers-Text).

Create Send Timestamps

---

exts/modPlayer.json

Embeds music tracker module file types like standard audio files using libopenmpt for playback. Includes options for interpolation and stereo separation.

Add modPlayer extension

---

exts/mediaControls.json

Fixes presence not broadcasting when album text was empty (Discord doesn't like empty strings)

Media Controls 1.0.8

---

exts/onePingPerDM.json

Really wanted to port over this plugin, so here it is!
Normally when someone DMs you multiple times, *ping ping ping ping* ***EXPLODES***
With this plugin, you only receive a ping for the first DM (until you read the channel). There are settings to allow `@everyone/@here` (in group chats) and `@mentions` to bypass the ping restrictions.
You can also pick whether to apply it to User DMs, Group Chats, or both.

Add onePingPerDM

---

exts/levantine.json

this levantine update fixes a bug when attempting to enable levantine without setting a mappings path. the fix should prevent looping loading screens and instead now load a default mappings path (which was the previously intended behavior)
commit with fixes can be seen here
https://github.com/floppydiskette/moonlight-exts/commit/7de62579608f4a9d65149ed55110d91f83033b02
however, the commit i'm using is the one after it
https://github.com/floppydiskette/moonlight-exts/commit/75abc45ccc50e13a03d303c66a8c88ee212373eb
this is because i had to update my deploy.yml to the new one for it to work properly

update levantine to v1.0.2

---

exts/memberCount.json

Fixes `ReferenceError: returnrequire is not defined` and crash.

Update memberCount to 1.0.2

---

exts/mentionAvatars.json

Shouldn't need another update unless something drastically changes with patched module, using remapped name as find now (sorry non-nightly users until next stable update)

Mention Avatars 1.0.3

---

exts/imageViewer.json

since discord cant decide whether or not they want to ship the ClipboardUtils rewrite on stable yet
fallback to normal media viewer if failed to load

Image Viewer 1.0.14

---

exts/whosWatching.json

Added a port of [this extension](https://github.com/fres621/vencord-whos-watching) by fres.
Slightly updated to also have a tooltip cause it always bothered me.
I hope this does not violate the privacy rule of the repository guidelines, as this information is already readily available to the user, it's just cumbersome to access.

Add whosWatching extension

---

exts/noNitroUpsell.json

Forces the UserStore's `premiumUser` to always be true, thus removing nitro popups and upsells throughout the app. I marked it Danger Zone as some aspects of the app obviously behave unexpectedly with this patch.
- Nitro Gifts will appear to be redeemable but just error when you attempt to.
- Soundboard sounds that you should not have access to will appear as usable, and appear to play, but they cannot be heard by others.

Add noNitroUpsell

---

exts/typingTweaks.json

Removed the extra style export, which not only created a duplicate style tag, but something about how I was exporting it was causing the extra style to just be `[object Object]` anyway.

typingTweaks 1.0.4->1.0.5

---

exts/removeTopBar.json

Fixes a patch that broke with a Discord updates, and makes the extension fail gracefully in case this happens again.

removeTopBar 1.0.3 -> 1.0.4

---

exts/katex.json
exts/ruby.json

A few general updates to the repository itself & fixes an issue in Ruby where `{{v,e,c,t,o,r,s},{a,n,d},{m,a,t,r,i,c,e,s}}` were causing a client freeze

Update katex and ruby

---

exts/typingTweaks.json

Backports the related fix from Vencord with changes for settings to not require a restart

typingTweaks 1.0.5 -> 1.0.6

---

exts/allActivities.json

I genuinely wish ill will to the developer on the activities team that decided that it was a good idea to filter out Playing activity types to only show AND SEND one (1) Playing activity. I do not know how in a million years your commit in discord/discord was ever approved and merged and I hope it gets reverted and you get fired for this blunder. Especially when they don't even offer a new activity type for non-games.

All Activities 1.1.1
