- exts/domOptimizer.json
- exts/emojiBlacklist.json
- exts/noInlineLinks.json
- exts/removeChannelIcons.json
> Add my exts (again)

- exts/css.json
changed css extension to adhere to the new format, also made some minor metadata changes
> add updated css extension

- exts/customReplyMention.json
small tiny little plugin that lets you customize the behavior of reply pings  
probably bad but it works
> Add Custom Reply Mention

- exts/css.json
puts css in documentElement to give it higher priority
> update css to 1.1.1

- exts/css.json
fixes issues with the extension attempting to load folders and non-css files
> update css to 1.2.0

- exts/osuTyping.json
> add osuTyping

- .github/workflows/pull_request.yml
- exts/copyAvatarUrl.json
Accidentally closed previous PR. Wait for develop release and for SWC changes to be on stable to merge this.
> Add copyAvatarUrl

- exts/noScreenSharePreview.json
- exts/trustAllDomains.json
Same as moonlight-mod/moonlight#51, let's wait until stable for merge.
> Update noScreenSharePreview and trustAllDomains for SWC changes

- exts/ruby.json
Adds ruby via `{{rb(rt)}}`
`{{猫(ねこ)}}を{{拾(ひろ)う}}` <ruby>猫<rp>(</rp><rt>ねこ</rt><rp>)</rp></ruby>を<ruby>拾<rp>(</rp><rt>ひろ</rt><rp>)</rp>う</ruby>
`{{我(wǒ)讲(jiǎng)日(rì)语(yǔ)}}` <ruby>我<rp>(</rp><rt>wǒ</rt><rp>)</rp>讲<rp>(</rp><rt>jiǎng</rt><rp>)</rp>日<rp>(</rp><rt>rì</rt><rp>)</rp>语<rp>(</rp><rt>yǔ</rt><rp>)</rp></ruby>
> Add ruby v1.0.0

- exts/imageViewer.json
> Add Image Viewer

- exts/mediaTweaks.json
Enlarge Video now works with Image Viewer enabled
> Update Media Tweaks to 1.0.1

- exts/platformStyles.json
- Fixes poput windows not getting frames when using `linux` style
> Platform Styles 1.0.1

- exts/imageViewer.json
Adds an input field when you click on the zoom percent label
> Image Viewer 1.0.3

- exts/greentext.json
- exts/shiftjis.json
- Add enlarge button to embedded videos
- Fix for Discord refactoring the media modal, which weirdly caused a startup crash
- Greentext
- ShiftJIS Codeblocks
> Media Tweaks 1.0.3, add Greentext and ShiftJIS Codeblocks

- exts/greentext.json
- exts/shiftjis.json
> Forgot dependencies on greentext and shiftjis

- exts/mediaTweaks.json
Fixes Enlarge Video and Inline Playback
> Media Tweaks 1.0.4

- exts/imageViewer.json
- Support for GIFV (Tenor/Imgur)
- Pixelate at >= 100% instead of just > 100% to fix some clarity issues on some images
> Image Viewer 1.0.6

- exts/nicknameTools.json
Nickname Tools is an extension like Show Me Your Name but includes some extra features
> nicknameTools 1.0.0

- exts/allActivities.json
- exts/mediaTweaks.json
> All Activities 1.0.1 + Media Tweaks 1.0.5

- exts/css.json
merges https://github.com/floppydiskette/moonlight-exts/pull/5
branch has been tested and should work fine, this is a very minor change
> CSS Update v1.4.1

- exts/imageViewer.json
> Image Viewer 1.0.7

- exts/platformIcons.json
> Platform Icons 1.0.1

- exts/imageViewer.json
> Image Viewer 1.0.9

- exts/chatTweaks.json
- Revert App to Bot
- Webhook tag
- Jump to blocked/ignored reply
- Hide blocked/ignored messages
> Chat Tweaks 1.0.1

- exts/mediaTweaks.json
> Media Tweaks 1.0.7

- exts/chatTweaks.json
- Always Show Owner Crown
- No Masked Link Paste
> Chat Tweaks 1.0.2

- exts/mediaControls.json
- Changes to Media Fetcher to add album, album artist, track number, total tracks and player name
- Option to display rich presence from media controls data (off by default, heavily configurable)
- Better progress bar
> Media Controls 1.0.2

- exts/platformIcons.json
- Toggles
- Always show mobile
> Platform Icons 1.0.3

- exts/chatTweaks.json
- No Reply Ping: Ping Exclusion List (with invert toggle)
> Chat Tweaks 1.0.3

- exts/mediaControls.json
- Fixes background for Nitro themes
> Media Controls 1.0.4

- exts/callTimer.json
- Move timer into connection status wrapper element because I'm picky
> Call Timer 1.0.5

- exts/allActivities.json
- exts/chatTweaks.json
- exts/mediaControls.json
- exts/mediaTweaks.json
- exts/noRpc.json
- exts/platformIcons.json
- exts/platformStyles.json
- exts/unminifyReactErrors.json
- exts/whoJoined.json
> Add advice fields to metadata for my extensions

- exts/customIdleTimeout.json
- exts/highlight.json
- exts/reverseImageSearch.json
Add settings advice to manifests.
> Update customIdleTimeout, highlight and reverseImageSearch

- exts/chatTweaks.json
> Chat Tweaks 1.0.4

- exts/chatTweaks.json
- Fix editing still being allowed when disabled
- ~~Dobule~~
> Chat Tweaks 1.0.5

- exts/dmDates.json
and some minor DM Favorites fixes
> Add DM Dates

- exts/dmDates.json
> DM Dates 1.0.1

- exts/decor.json
To Cyn: Please look over this thoroughly and test it, I haven't done much of that myself lol
> decor 1.1.0

- exts/pronouns.json
fixes a layout shift when pronouns are loaded
> pronouns: update

- exts/alwaysFocus.json
- exts/copyAvatarUrl.json
- exts/customIdleTimeout.json
- exts/freeScreenShare.json
- exts/highlight.json
- exts/inviteToNowhere.json
- exts/noHelp.json
- exts/noScreenSharePreview.json
- exts/noSmoothScrolling.json
- exts/reverseImageSearch.json
- exts/showAllRoles.json
- exts/spotifySpoof.json
- exts/trustAllDomains.json
- exts/viewJson.json
Mostly meta changes, some changes to make patches use identifier escapes, some changes to using mapped modules.
> large large big

- exts/decor.json
- exts/devBanner.json
- exts/imageViewer.json
- exts/mediaControls.json
Can I join the "update for mappings and donate link" PR train too?
> medium medium somewhat

- exts/richNotifications.json
Adds a plugin that makes your toast notifications prettier. Currently the only special things are: spoiler characters get turned into the unicode block symbol, image attachments appear inline, avatars are rounded
> Add Rich Notifications (Windows-only plugin)

- exts/richNotifications.json
> richnotifs don't show spoilered images

- exts/decor.json
> decor 1.1.2

- exts/richNotifications.json
Photoshoot fresh, looking like wealth
I'm 'bout to call the paparazzi on myself
> richNotifications 1.0.2: Don't show NSFW images in toast

- exts/richNotifications.json
Intertwined by your love (Intertwined by your love)
Chemistry uprooted between us (Uprooted between us)
Its a sentimental lust (It's a sentimental lust)
Craving warmth and I think that we're
> richNotifications 1.0.3: Fix wrong messages showing toasts, caused by improper confidence in order of execution

- exts/displaySummaries.json
Adds the Display Summaries extension
meow
> Add Display Summaries

- exts/selectivelyReduceMotion.json
discord trivia: use reduced motion does not work in the view reactions modal
> selectivelyReduceMotion: 1.1.0

- exts/richNotifications.json
They say it′s better to have loved and lost than never loved at all
Just love the lust you'll have the leap without the fall
> richNotifications 1.1.0: Delete old cached files after 15s

- exts/toggleReadNotificationsAloud.json
Press Ctrl+Shift+M to toggle the Text-to-Speech Notifications setting between 'For current selected channel' and 'Never'.
sorry if i missed something it's 2am and i'm tired
> Create Toggle Text-to-Speech Notifications

- exts/pronouns.json
> pronouns: 1.2.2

- exts/selectivelyReduceMotion.json
> selectivelyReduceMotion: 1.1.1

- exts/pronouns.json
> pronouns: 1.2.3

- exts/freeMoji.json
Based on https://github.com/maisymoe/strife/tree/master/plugins/Freemoji
> Add Free Nitro Emoji extension

- exts/freeMoji.json
Drop emoji size to 48px and animate if possible
> Freemoji 1.0.3

- exts/oneko.json
Added more character skins (thanks @danielah05!)
> oneko 1.1.0

- exts/pronouns.json
the third proofreading incident
going insane
> pronouns: 1.2.5

- exts/modPlayer.json
> modPlayer 1.0.2

- exts/mediaControls.json
Support for Windows (Store) versions of Spotify when excluding it from rich presence
> Media Controls 1.0.7

- exts/remind-me.json
- Fixes a crash when opening the Inbox with embeds that have numeric color values
> remind-me 1.0.1

- exts/cloneExpressions.json
built in a way to do cloning stickers eventually
> cloneExpressions: 1.0.0

- exts/ruffle.json
Adds embeds for Flash files via Ruffle. Keeping this as a draft until it's proven relatively safe.
> Ruffle extension

- exts/ruffle.json
You may have noticed that sometimes Ruffle won't load if the connection is slow. Or maybe you didn't. Anyway, I fixed it.
I love that TV show you′ve watched
Since like sixth grade
I wish that we grew up together
Is it too late?
I'm not bilingual, it′s a challenge
Tryna read your body language here tonight
> Ruffle 1.0.1: more reliable postMessage

- exts/ruffle.json
* Add file name and file size to ruffle preloader embed
* Add download SWF button to preloader
i'm too lazy to add sadboy lyrics here
hi marsh
> Ruffle 1.1.0

- exts/cloneExpressions.json
> cloneExpressions: 1.2.0

- exts/ruffle.json
Apparently I forgot to send this in
> Ruffle 1.1.1: Add fun and dangerZone tags

- exts/cloneExpressions.json
fixed clone emoji context menu item not appearing in the emoji picker
> cloneExpressions: 1.2.1

- exts/showMediaOptions.json
mainly allows you to copy urls to stickers, but also some other things that would appear in the message context menu
> showMediaOptions: 1.0.0

- exts/richNotifications.json
role pings were throwing an error before because i don't know how stores work :^)
> richNotifications 1.1.1: Fix role pings

- exts/replyChain.json
Closes the reply chain component on escape, when you're scrolled all the way down in the in the current channel/DM.
> replyChain: 1.1.0

- exts/replyChain.json
Refactor to use the built-in mappings.
> replyChain: 1.1.1

- exts/mediaTweaks.json
Fixes Enlarge Video Button not showing on embed videos with no file extension
> Media Tweaks 1.0.10

- exts/notificationVolume.json
they changed the function i was finding by 1 character (they removed an _)
> Update notificationVolume 1.0.1

- exts/remind-me.json
- Restores Inbox tab for Reminders
> remind-me v1.0.2

- exts/clearUrls.json
> Add clearUrls

- exts/imgTitle.json
> Add imgTitle

- exts/neatSettingsContext.json
and add `environment` to Platform Styles
> Add Neat Settings Context Menu

- exts/expandStatus.json
> expandStatus: 1.0.1

- exts/betterEmbedsYT.json
Currently has copyright bypass and adblock.
> Add Better YouTube Embeds

- exts/modPlayer.json
Fixes a crash I noticed when testing new Discord stuff.
(I was gonna upload a module right here in the PR but GitHub won't let me do that so here's the modarchive page instead: https://modarchive.org/module.php?207919)
> modPlayer 1.0.4

- exts/staffTags.json
> Add staffTags

- exts/betterEmbedsYT.json
> Better YouTube Embeds 1.1.0

- exts/platformStyles.json
> Platform Styles 1.0.2

- exts/betterEmbedsYT.json
> Better YouTube Embeds 1.1.1

- exts/clearUrls.json
- exts/imgTitle.json
- exts/translateText.json
- Adds translateText: Adds a translate button to context menus when you select text. Interacts with the Google Translate API.
- imgTitle 1.0.1: support for avif images
- clearUrls 1.0.1: fix typos in description
> Add translateText, imgTitle 1.0.1, clearUrls 1.0.1

- exts/decor.json
- exts/inAppNotifications.json
- exts/mediaControls.json
Crash fixes for latest canary (won't break stable)
(also minor rich presence change to Media Controls)
> In App Notifications 1.0.4 + Decor 1.1.4

- exts/betterEmbedsYT.json
Mess with player vars a bit to make the embed player look neater
> Better YouTube Embeds 1.1.2

- exts/inAppNotifications.json
Attempt to fix loading issues I cannot replicate by deduction of making finds more unique
> In App Notifications 1.0.5

- exts/decor.json
- exts/devBanner.json
- exts/mediaControls.json
(at least it doesn't crash for me on Canary and there was a Stable update, I barely tested this lol)
> Fix a buncha stuff

- exts/mfm.json
Adds support for MFM (Markup language For Misskey) in code blocks using \`\`\`mfm \`\`\`
Some examples:
````
```mfm
Bold
**太字**
Shrink
<small>MisskeyでFediverseの世界が広がります</small>
Quote
> MisskeyでFediverseの世界が広がります
Center align
<center>MisskeyでFediverseの世界が広がります</center>
Yomigana (Ruby characters)
$[ruby Misskey ミスキー]
Code (Inline)
`<: "Hello, world!"`
Flip
$[flip MisskeyでFediverseの世界が広がります]
$[flip.v MisskeyでFediverseの世界が広がります]
$[flip.h,v MisskeyでFediverseの世界が広がります]
Font
$[font.serif MisskeyでFediverseの世界が広がります]
$[font.monospace MisskeyでFediverseの世界が広がります]
$[font.cursive MisskeyでFediverseの世界が広がります]
$[font.fantasy MisskeyでFediverseの世界が広がります]
Blur
$[blur MisskeyでFediverseの世界が広がります]
Search
misskey 検索
Foreground & background colors
$[fg.color=f00 赤字]
$[bg.color=ff0 黄背景]
Border …
> Add Markup language For Misskey

- exts/mfm.json
Reverts moonlight-mod/extensions#208.
Stalling CI for no explainable reason.
> Revert "Add Markup language For Misskey"

- exts/modPlayer.json
A regex broke. It's fixed now.
> modPlayer v1.0.5

- exts/dmDates.json
> DM Dates 1.0.2

- exts/modPlayer.json
yeah sure okay whatever discord
> modPlayer 1.0.6

- exts/dmFavorites.json
> DM Favorites 1.0.4

- exts/whoJoined.json
> Who Joined 1.0.1

- exts/notificationContent.json
yes i bumped the version this time
> Update notificationContent to support latest discord blah blah

- exts/pronouns.json
component editor is borked seemingly so won't render but store works again now
> pronouns: 1.2.7

- exts/lastFmRpc.json
seems to work fine for me, only real change i made is decreasing the (default) update interval from 16 -> 10 seconds and adding the interval as a setting
> add last.fm rpc extension ported from vencord

- exts/silenceTyping.json
this just patches the typing dispatch out, like the [vencord extension](https://github.com/Vendicated/Vencord/blob/main/src/plugins/silentTyping/index.tsx) but doesn't include any of the settings
> add silence typing extension

- exts/mediaControls.json
> Media Controls 1.0.12

- exts/nicknameTools.json
> Update nicknameTools to 1.0.5

- exts/allActivities.json
didnt test opening profiles and didnt see post in #support cause forum read states suck
> All Activities 1.0.7

- exts/imageViewer.json
i need to sleep i didnt notice the syntax error guh
> Image Viewer 1.0.15

- exts/imageViewer.json
> Image Viewer 1.0.16

- exts/remind-me.json
- Fix bookmark actions for non-Nitro users
> remind-me v1.0.3

- exts/mediaTweaks.json
- Enlarge Video button components v2 crash fix
- Voice Message Download Button
> Media Tweaks 1.0.13

- exts/copyWebp.json
- exts/greentext.json
- exts/hideBlocked.json
- exts/inAppNotifications.json
- exts/jumpToBlocked.json
- exts/mediaControls.json
- exts/platformIcons.json
> some sort of clever pr title

- exts/inAppNotifications.json
> In App Notifications 1.0.9

- exts/lastFmRpc.json
- exts/muteGuildOnJoin.json
- exts/silenceTyping.json
title, also changed the other extensions i had pointing to the mirror to point to the source repo instead
> feat: add muteGuildOnJoin

- exts/svgEmbed.json
rehomed <:blobcatcozy:1145727546747535412>
> Add SVG Embed

- exts/imageViewer.json
> imageViewer 1.0.19

- exts/cloneExpressions.json
> cloneExpressions: 1.2.6

- exts/freeStickers.json
- exts/whosWatching.json
Port of the sticker functionality of FakeNitro from Vencord. I made sure to publish the repo under GPL3 since much of the code is derived from FakeNitro.
Still not sure if that is all thats needed, though.
> Add freeStickers & Update whosWatching

- exts/favouriteGifSearch.json
Adds a search bar to the favourites tab in the GIF picker https://github.com/MeguminSama/moonlight-extensions/tree/main/src/favouriteGifSearch
> Add favouriteGifSearch

- exts/gameActivityToggle.json
- exts/userSettingsApi.json
Missing features:
- Old icon for gameActivityToggle is not toggleable yet
NB: These extensions are GPL.
Can someone let me know if I did the library extension (userSettingsApi) correctly? Thanks.
> userSettingsApi & gameActivityToggle direct ports from Vencord

- exts/removeTopBar.json
[Cynosphere's PR](https://github.com/Enovale/moonlight-extensions/pull/1) plus a small change on my part.
> removeTopBar 1.0.2 -> 1.0.3

- exts/doubleClickToJoin.json
fix unwanted behaviour, bump version
> update doubleClickActions to 1.0.3

- exts/favouriteGifSearch.json
- Fixed non-tenor links not showing in search results
- Improved search results with weighting based on filename, query params, and website source.
diff: https://github.com/MeguminSama/moonlight-extensions/compare/3441328b412b8631df310c0ff0d1e22d4492f71f...3cadb95e6cd613bf30a5bd609577f3fbf8c4cd94
> update: favouriteGifSearch

- exts/whosWatching.json
Fixes crash when streaming in DMs
> Update whosWatching 1.0.3 -> 1.0.4

- exts/freeStickers.json
Fixed bug with popout messages
> freeStickers: 1.0.2 -> 1.0.3

- exts/removeTopBar.json
> removeTopBar 1.0.4 -> 1.0.5

- exts/selectivelyReduceMotion.json
fascinating how this breaks in one day
> selectivelyReduceMotion: 1.6.1

- exts/imageViewer.json
> Image Viewer 1.0.22

- exts/streamQualityWorkaround.json
Fixed the PanelButton dependency that caused crashes on the most recent update.
> Update streamQualityWorkaround 1.1.0 -> 1.1.1

- exts/quickDelete.json
Quick Delete: hold backspace + click on a message. If the message is yours or you have MANAGE_MESSAGES permission, delete message.
> Add quickDelete
